# https://www.kucoin.com/ru/trade/futures/CYSUSDTM
# https://www.kucoin.com/ru/trade/futures/MYXUSDTM
# https://www.kucoin.com/ru/trade/futures/GFUSDTM
# https://www.kucoin.com/ru/trade/futures/IRUSDTM
# https://www.kucoin.com/ru/trade/futures/ARCUSDTM
# https://www.kucoin.com/ru/trade/futures/IRYSUSDTM
# https://www.kucoin.com/ru/trade/futures/FRAXUSDTM
# https://www.kucoin.com/ru/trade/futures/GUSDTM
# https://www.kucoin.com/ru/trade/futures/AZTECUSDTM
# https://www.kucoin.com/ru/trade/futures/MIRAUSDTM